### ISSUE TITLE
ACMAPP: Create SqlBuilder Class

### ISSUE THREAD

**Issue by sambutler1017** [cse-uprc/acm-app-microservice#11]
### SqlBuilder class
- This will take in a file of type `.acmsql`, this will then go through the SQL builder and get the requested URL based on the given name passed in. 
- An enum will need to be created that has the common sql clauses:
   - `WHERE`, `SELECT`, `FROM`, `IF`
   - Any other sql tags being used can be added
- The class will need to be passed in:
   - The file that the query will be looking in
   - The params passed in, to replace optional values in a query
```
@Component
public class SqlBuilder {
   private static String queryFile;
   private static Map<String, Set<?>> params;

   public String getQueryFile() {
	return queryFile;
   }

   public void setQueryFile(String file) {
	queryFile = file;
   }

   public Map<String, Set<?>> getParams() {
	return params;
   }

   public void setParams(Map<String, Set<?>> values) {
	params = values;
   }
}
```

### File Locations
- The default file location for the SQL builder that it will be looking in is `src/main/resources/dao`
- This will be the default location for any dao classes that contain queries in them

### Functionality of Class
- What it should be able to do is I call it like so:
```
Map<String, Set<?>> params = new HashMap<>();
params.put("userId", Sets.newHashSet(1));

sqlBuilder.setQueryFile("userDAO");
sqlBuilder.setParams(params);

String query = sqlBuilder.getSql("getUserById");
```
- The corresponding file that the SQL builder will be using is the `userDAO` which would look something like:
```
@NAME(getUserById)
	SELECT 
	    u.user_id,
	    u.first_name,
	    u.last_name,
	    u.email,
	    u.app_access,
	    wr.role_type,
	    sr.region
	FROM
	    users u
	WHERE u.user_id = :userId:
```
- So what it would do is find the name given to the sqlbuilder, which in this case is `getUserById`. 
- It read the query line by line making sure it has no variables that needed to be inserted from the passed in params.
- In this example there is, which is `userId`. It would see that varaible and insert it in that line. So the resulting query returned would look like:
```
	SELECT 
	    u.user_id,
	    u.first_name,
	    u.last_name,
	    u.email,
	    u.app_access,
	    wr.role_type,
	    sr.region
	FROM
	    users u
	WHERE u.user_id = 1
```
- The checks needed would be to first check to make sure that the parameter in the query exists in the parameters that are passed in. 
   - If not then throw an error
- Next need to create an enum that has this value id, which what we will be using is a colon (`:`)
- They should be allowed to have conditional checks in the sql as well, for example:
```
@WHERE(:userId:)
	uc.user_id = :userId:
```
- This statement would only insert this where clause if a parameter called `userId` was passed in.

### Tasks
- [x] Create enum that has all the query clauses needed
- [x] Create getters and setters needed to set the file location and parameters
- [x] Create enum containing the value id 
- [x] Create methods needed to implement this functionality
